version: '3'
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    command: "--storageEngine wiredTiger"
    volumes:
      - ./mongofiles:/data/db
  collector:
    build: ./
    image: vistrcm/statcollector
    depends_on:
      - mongo
    ports:
      - 8080:8080
    command: "--mongoUrl mongodb://mongo/stats"
