version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: "--storageEngine wiredTiger --auth"
    volumes:
      - ./mongofiles:/data/db
  collector:
    build: ./
    depends_on:
      - mongo
    ports:
      - 8080:8080
    command: "--mongoUrl mongodb://collector:Ci1aTh1ooshiib6iepha4oongaeSho@mongo/stats"
