version: '3'
services:
  mongo:
    image: mongo:4
    command: "--auth"
    ports:
      - 27017:27017
    volumes:
      - ./mongofiles:/data/db
  collector:
    build: ./
    image: vistrcm/statcollector
    environment:
      - MONGO_USER
      - MONGO_PASS
    depends_on:
      - mongo
    ports:
      - 8080:8080
    command: "--mongoUrl mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/stats"
